server:
  port: 8088
spring:
  profiles:
    active: dev # 根据部署环境调整 dev 或 prod
  application:
    name: megatron
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      # 自动创建表采用InnoDB引擎
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:                             # 配置用户认证
    user:
      name: sct
      password: sct2020
      role: USER

logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

